const elements_of_pure_economics = {
  title: "Elements of Pure Economics",
  subtitle: "Or the Theory of Social Wealth",
  author: "Léon Walras",
  synopsis:
    "The father of general equilibrium theory and the grandfather of input/output analysis proves the Classical Economists right through value-neutral mathematics while criticizing their methods throughout. Leon Walras (1834-1910) is one of a kind and this book, translated by the able Walrasian scholar, Northwestern University's William Jaffe, is one of a kind.<br/><br/>Reading Professor Walras’ differentiating of art, science and ethics is alone reason to buy the book. “The Elements” was first published 140 years ago and appreciation of its 42 lessons still hasn’t reached its deserved level among economists not to mention the lay public. Its treasures remain largely buried under its mathematical notation and unintegrated with the modern-day economic psyche. Sad.<br/><br/>To witness a real scientist is to behold Walras proving J.B. Say correct without really wanting to do so. And, like all great scientists, Walras inevitably got himself into trouble with those living with sacred cows. Socialists dislike him because he proved private enterprise maximizes material well-being for all while libertarians dislike him because he dared say that efficiency might not be the end of the discussion.<br/><br/>There are reasons to question Walras’ scientific methods – mathematical treatment of a problem often involves making simplifying assumptions – as well as statements pregnant with political dynamite. Prof. Murray Rothbard, in his essay “Breaking Out of the Walrasian Box: The Cases of Schumpeter and Hansen,” is correct when he writes that mathematization tends to cut off “the messy and fuzzy uncertainties and inevitable errors of real-world entrepreneurship and human actions.” And this passage from “The Elements” (p. 61) is sure to raise eyebrows and provoke calls to French friends asking for the cultural context and questioning the accuracy of the translation – “Obviously all one can do about manifestations of the forces of nature is to identify, verify and explain them; but in dealing with workings of the human will, not only is it possible to identify, verify, and explain them, but having done that one can then control them.” Who or what is the “one” in that last sentence?<br/><br/>",

  image: "/assets/images/books/non-fiction/acedemic/economics/elements-of-pure-economics.jpg",
  link_pdf: "https://b-ok.cc/book/2956937/cfa635",
  link_epub: "https://b-ok.cc/book/23087441/532711",
  link_amazon: "https://www.amazon.ca/Elements-Pure-Economics-L%C3%A9on-Walras/dp/0415607310/ref=sr_1_1?crid=1JJSML14MOKEH&keywords=elements+of+pure+economics&qid=1663519403&sprefix=elements+of+pure+economics%2Caps%2C129&sr=8-1",
  link_indigo: "https://www.chapters.indigo.ca/en-ca/books/elements-of-pure-economics/9781134560028-item.html?ikwid=Elements+of+Pure+Economics&ikwsec=Home&ikwidx=0#algoliaQueryId=7212d8ea04c9eb42523de0e6e592095c",
  link_handmade: "#",
};
