const progress_and_poverty = {
  title: "Progress and Poverty",
  subtitle:
    "An Inquiry into the Cause of Industrial Depressions and of Increase of Want with Increase of Wealth; The Remedy ",
  author: "henry george",
  synopsis:
    "In Progress and Poverty, economist Henry George scrutinizes the connection between population growth and distribution of wealth in the economy of the late nineteenth century.<br/><br/>The initial portions of the book are occupied with refuting the demographic theories of Thomas Malthus, who asserted that the vast abundance of goods generated by an economy's growth was spent on food. Consequently the population rises, keeping living standards low, poverty widespread, and starvation and disease common.<br/><br/>Henry George had a different attitude: that poverty could be solved and economic progress preserved. To prove this, he draws upon decades of data which show that the increase in land prices restrains the amount of production on said land; business owners thus have less to pay their workers, with the result being mass poverty especially within cities.<br/><br/>The radical solution George proposes is a land value tax, whereby owners of land must pay a levy on their holdings. Thus money is diverted directly from landowners, to be spent on alleviating the poverty of workers, improving the infrastructure and environment of urban and rural areas, and even giving every citizen a basic income to cover their necessities.<br/><br/>George is also concerned with the cyclical nature of the economy, which by the latter part of the 19th century clearly followed cycles of boom and bust. This instability is further aggravated by spikes in land prices and consequently rents, whereby both producers - such as factory builders and farmers - and workers are displaced. Thus, Henry George doubles down on his idea for the land value tax, highlighting its efficiency and the fact that land - unlike resources or labor - is a fixed and easily quantified thing.<br/><br/>Divided into ten books, which in turn comprise between two and five chapters each, Progress and Poverty sequentially proposes, and discusses the implementations, of this economic reform. The book was enormously popular with the American public; written in a plain but engaging style, the powerful argument George makes would impact economists and the public consciousness alike for decades to follow.",
  image:
    "<img src='/assets/images/books/non-fiction/acedemic/economics/progress-and-poverty.jpg' class='img' alt=''>",
  link_pdf:
    "<a class='fa fa-file-pdf' href='https://b-ok.cc/book/23087028/ebeb2c' target='_blank'></a>",
  link_epub:
    "<a class='fa fa-book-open' href='https://b-ok.cc/book/11929550/e7bca7' target='_blank' ></a>",
  link_amazon:
    "<a class='fab fa-amazon' href='https://www.amazon.ca/Progress-Poverty-Industrial-Depressions-Increase/dp/1975767098/ref=sr_1_1?crid=2I4Q646IYZTL2&keywords=poverty+and+progress&qid=1663518998&sprefix=poverty+and+progress%2Caps%2C113&sr=8-1' target='_blank' ></a>",
  link_indigo:
    "  <a class='' href='https://www.chapters.indigo.ca/en-ca/books/progress-and-poverty/9781279940709-item.html?ikwid=Progress+and+Poverty&ikwsec=Home&ikwidx=0#algoliaQueryId=f08fbdd1152b272466696aff62adb80c' target='_blank'>indigo</a>",
  link_handmade: "<a class='fa fa-book' href='#' target='_blank'></a>",
};
